name:                Alexis Manuel
title:               Alexis Manuel
url:                 https://alexismanuel.com
enforce_ssl:         alexismanuel.com
baseurl:             ""
include:             ['_pages']
exclude:             []
author:              Alexis Manuel

plugins:
  - jekyll-redirect-from
  - jekyll-last-modified-at
  - jemoji

sass:
  sass_dir:          _sass
  style:            :compressed

collections:
  gpcs:
    output: true
    permalink: /gpcs/:path
  notes:
    output: true
    permalink: /notes/:path

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
  - scope:
      path: "_notes/**/*.md"
    values:
      layout: "note"
  - scope:
      path: "_gpcs/**/*.md"
    values:
      layout: "gpc"