[build]
  command = "BUNDLE_WITHOUT=development:test bundle install && bundle exec jekyll build"
  publish = "_site"

[build.environment]
  RUBY_VERSION = "3.2.2"
  BUNDLE_DEPLOYMENT = "true"
  BUNDLE_PATH = "vendor/bundle"
  BUNDLE_WITHOUT = "development:test"